### ISSUE TITLE
Plugin wraps each code line into a separate tag(s)

### ISSUE THREAD

**Issue by certainlyakey** [crilleengvall/Wordpress-tinyMCE-pre-code-wrapper#4]
Hi! Thanks for the plugin.

I noticed though one thing: when you click the button with some multiline text selected, each line gets wrapped into `<code><pre>` tag pair or one `<code>` tag. This probably should not be like this and the whole text should be wrapped into one `<code>` and one `<pre>` tag.

My WP version is 4.7.5.

**Comment by crilleengvall** [comment]
Hi!

Thanks for reporting this bug. I'll take a look at it as soon as possible.

**Comment by crilleengvall** [comment]
Not sure if you are using this plugin anylonger since it was a long time since this bug was reported. 
However i just committed an update to it which takes care of the issue you described above if you'd like to test it @certainlyakey

**Comment by certainlyakey** [comment]
That's a great news, thanks! I hope to test it soon.

**Comment by certainlyakey** [comment]
I did some testing, and now it wraps all the lines! Thanks @crilleengvall! Closing the ticket then.
